apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wms
  namespace: argocd
spec:
  description: project with role description
  sourceRepos:
  - 'https://github.com/coco2908/argocd-example-apps.git'

  destinations:
  - namespace: '*'
    server: '*'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: ci-role
    description: Sync privileges for project-with-role
    policies:
    - p, proj:wms:ci-role, applications, sync, wms/*, allow
