apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fms
  namespace: argocd
spec:
  description: Project fms
  sourceRepos:
  - 'https://github.com/coco2908/argocd-example-apps.git'

  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
